### ISSUE TITLE
Handle markup in heading properly

### ISSUE THREAD

**Issue by vithar** [Flet/github-slugger#7]
GitHub handles this code

```
== Why does BEM not recommend using elements within elements (`block__elem1__elem2`)?
```
as

#why-does-bem-not-recommend-using-elements-within-elements-block__elem1__elem2

But `github-slugger` as

#why-does-bem-not-recommend-using-elements-within-elements-codeblock__elem1__elem2code

See https://github.com/bem/bem-method/blob/bem-info-data/faq/faq.en.md#why-does-bem-not-recommend-using-elements-within-elements-block__elem1__elem2

//cc @tadatuta

**Comment by wooorm** [comment]
```js
var Slugger = require('github-slugger');
var slugger = new Slugger();
var result = slugger.slug('Why does BEM not recommend using elements within elements (block__elem1__elem2)?');
console.log(result);
```

Yields:

```txt
why-does-bem-not-recommend-using-elements-within-elements-block__elem1__elem2
```

Compared to GH:

```txt
why-does-bem-not-recommend-using-elements-within-elements-block__elem1__elem2
```

[Proof](https://github.com/bem/bem-method/blob/bem-info-data/faq/faq.en.md#why-does-bem-not-recommend-using-elements-within-elements-block__elem1__elem2).

Pretty sure they’re the same, or is it my eyes? I’m guessing this has to do with what you provide to `slugger`.

**Comment by vithar** [comment]
# cat 1.js
var Slugger = require('github-slugger');
var slugger = new Slugger();
var result = slugger.slug('Why does BEM not recommend using elements within elements (<code>block__elem1__elem2</code>)?');
console.log(result);

node 1.js
why-does-bem-not-recommend-using-elements-within-elements-codeblock__elem1__elem2code

**Comment by wooorm** [comment]
Ah, I see where you’re coming from.

github-slugger is not a markdown parser / stripper or HTML parser / stripper. It expects just the text in a heading (think `textContent` instead of `innerHTML`, if you’re familiar with the DOM interface of elements).

If you’re dealing with HTML, I suggest something like [`azer/strip`](https://github.com/azer/strip) (it’s been republished), or when in the browser `textContent`. For markdown, my project [`wooorm/remark`](https://github.com/wooorm/remark) might be interesting.

I feel this is out of scope and intent to close this issue. @Flet, thoughts?

**Comment by Flet** [comment]
Indeed @wooorm you're spot on :)
